FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env

COPY BusTour/otc-infrastructure-core ./app/otc-infrastructure-core
COPY BusTour/src ./app/src

WORKDIR /app/src/BusTour.Scheduler

RUN dotnet publish ./BusTour.Scheduler.csproj -c Stable -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime

WORKDIR /app

COPY  --from=build-env /app/src/BusTour.Scheduler/out ./

ENV ASPNETCORE_ENVIRONMENT=Stable_Yandex

ENTRYPOINT ["dotnet", "BusTour.Scheduler.dll"]