version: "3.9"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.develop
        container_name: bustour_api     
        ports:
            - 55555:80             