version: "3.9"
services:
  site:
    container_name: "bus_site"
    build: .
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/nuxt-app
    command: tail -F anything
    # command: npm run dev
    # command: sh -c "npm install && npm run dev"