version: '3.9'

services:
  bus_site:
    container_name: "bus_site"
    build:
      context: ../../../
      dockerfile: ./BusTour/src/BusTour.WebSite/${DEVOPS_DOCKERFILE}
      args:
        buildno: ${DEVOPS_BUILD}
    restart: unless-stopped
    ports:
      - "3002:3002"
    #volumes:
      #- .:/usr/src/nuxt-app
    labels:
      SITE_URL: ${DEVOPS_SITE_URL}
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "site_status"
        env: "os"
