version: '3.9'

services:
  bus_api:
    container_name: "bus_api"
    build:
      context: ../../../
      dockerfile: ./BusTour/src/BusTour.WebApi/${DEVOPS_DOCKERFILE}
      args:
        buildno: ${DEVOPS_BUILD}
    restart: unless-stopped
    ports:
      - "3001:80"
    volumes:
      - /var/log/app:/app/logs
    labels:
      SITE_URL: ${DEVOPS_SITE_URL}
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "site_status"
        env: "os"
